<?php
ini_set('include_path', ini_get('include_path') . PATH_SEPARATOR . '../../' . PATH_SEPARATOR. '../' . PATH_SEPARATOR . '../../../' . PATH_SEPARATOR);
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function ($class) {
        static $classes = null;

        if ($classes === null) {
            $classes = array(
                /*--- controller ---*/
                'Database' => 'common/DBHelper.php',
                'Menu' => 'model/Menu.php',
                'Model' => 'model/Model.php',
            );
        }
        $cn = trim($class);
        if (isset($classes[$cn])) {
            require $classes[$cn];
        }
    },
    true,
    false
);